# Generated by Django 5.2.8 on 2025-11-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_poster_alter_sectiontag_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
