# Generated by Django 5.2.8 on 2025-11-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('poster', models.ImageField(blank=True, upload_to='static/Uploaded_posters/')),
                ('director', models.CharField(max_length=70)),
                ('actors', models.TextField()),
                ('release_date', models.DateField()),
                ('country', models.CharField(max_length=70)),
                ('platform', models.CharField(max_length=70)),
                ('summary', models.TextField()),
                ('rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('genres', models.ManyToManyField(to='movies.genre')),
                ('similar_movies', models.ManyToManyField(blank=True, to='movies.movie')),
            ],
        ),
    ]
