# Generated by Django 5.2.8 on 2025-11-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='platform',
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(blank=True, to='movies.country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='platform',
            field=models.ManyToManyField(blank=True, to='movies.platform'),
        ),
    ]
