# Generated by Django 5.2.7 on 2025-11-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('poster', models.ImageField(upload_to='')),
                ('director', models.CharField(max_length=70)),
                ('actors', models.TextField()),
                ('release_date', models.DateField()),
                ('country', models.CharField(max_length=70)),
                ('platform', models.CharField(max_length=70)),
                ('summary', models.TextField()),
                ('rate', models.FloatField()),
                ('genres', models.ManyToManyField(to='movies.genre')),
                ('similar_movies', models.ManyToManyField(blank=True, to='movies.movie')),
            ],
        ),
    ]
