# Generated by Django 5.2.7 on 2025-11-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('director', models.CharField(max_length=70)),
                ('production_year', models.DateField()),
                ('actors', models.TextField()),
                ('country_company', models.CharField(max_length=70)),
                ('summery', models.TextField()),
                ('rate', models.FloatField()),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
