# Generated by Django 5.2.8 on 2025-11-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('Director', 'Director'), ('Actor', 'Actor')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='static/posters')),
                ('summary', models.TextField()),
                ('rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('release_date', models.DateField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('country', models.ManyToManyField(blank=True, to='movies.country')),
                ('genre', models.ManyToManyField(to='movies.genre')),
                ('similar_movies', models.ManyToManyField(blank=True, to='movies.movie')),
                ('actors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'Actor'}, related_name='acted_movies', to='movies.people')),
                ('director', models.ManyToManyField(limit_choices_to={'role': 'Director'}, related_name='directed_movies', to='movies.people')),
                ('platform', models.ManyToManyField(blank=True, to='movies.platform')),
            ],
        ),
        migrations.CreateModel(
            name='SectionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('movies', models.ManyToManyField(to='movies.movie')),
            ],
        ),
    ]
