# Generated by Django 5.2.8 on 2025-11-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='sectiontag',
            name='movies',
            field=models.ManyToManyField(blank=True, to='movies.movie'),
        ),
    ]
